# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Update dependencies for CDK stack package
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-name: "@aws-cdk/assert"
          - dependency-name: "@types/jest"
          - dependency-name: "@types/node"
          - dependency-name: "@types/puppeteer"
          - dependency-name: "aws-cdk-lib"
          - dependency-name: "constructs"
          - dependency-name: "jest"
          - dependency-name: "puppeteer-lambda"
          - dependency-name: "ts-jest"
          - dependency-name: "typescript"
          # Allow updates for all Castle packages
          - dependency-name: "@castlefinance*"
      ignore:
          - dependency-name: "@castlefinance*"
            update-types: ["version-update:semver-major"]

    # Update dependencies for src/shared package
    - package-ecosystem: "npm"
        directory: "/src/shared"
        schedule:
            interval: "daily"
        allow:
            - dependency-name: "*"

    # Update dependencies for normalize-raw-transaction lambda
    - package-ecosystem: "npm"
        directory: "/src/lambdas/normalize-raw-transaction"
        schedule:
            interval: "daily"
        allow:
            - dependency-name: "aws-sdk"

    # Update dependencies for download-raw-transaction lambda
    - package-ecosystem: "npm"
        directory: "/src/lambdas/download-raw-transaction"
        schedule:
            interval: "daily"
        allow:
            - dependency-name: "aws-sdk"

    # Update dependencies for index-transaction-ids lambda
    - package-ecosystem: "npm"
        directory: "/src/lambdas/index-transaction-ids"
        schedule:
            interval: "daily"
        allow:
            - dependency-name: "aws-sdk"
